### ISSUE TITLE
UWP Broker and UWP Client cannot running on same device 

### ISSUE THREAD

**Issue by nikirova** [gnatmq/gnatmq#41] opened 2017-04-21 08:38 UTC
Hello,

I have develop a UWP mqtt broker using _GnatMQ_ and a UWP mqtt client using _M2Mqtt_. My problem is when the broker starts and client trying to connect with this broker, I get a connection exception (both broker and client are running on Windows IoT 10 core).
Otherwise, when I start the UWP broker on another device located on same local network (eg my laptop) the UWP client is connected and exchanges messages with broker.
My question is if UWP broker and UWP client can run on same device (Windows IoT 10 core).

Thank you,
Niki

**Comment by BlueBasher** [comment] 2017-05-20 11:57
I had the same issue. On Windows IoT Core app's aren't allowed to communicate with each other using localhost.
You need to add a loopback exempt for both app's (Broker and client app).
This can be done by executing checknetisolation loopbackexempt -a -n=<app family name>
Running that command can be done in the Windows Device Portal => Processes => Run command
The app family name can be found in Windows Device Portal => Apps Manager => Details for the app.
If the PackageFullName is AppName_1.00.0_arm__SomeValue the AppFamilyName is AppNameSomeValue.

I figured this out with the help of http://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback

**Comment by nikirova** [comment] 2017-05-22 09:11
Could you please advise what network capabilities should have for both apps?

Thank you in advance!
Niki

**Comment by BlueBasher** [comment] 2017-05-23 15:55
For both apps I have these capabilities:
    <Capability Name="internetClient" />
    <Capability Name="internetClientServer" />
    <Capability Name="privateNetworkClientServer" />

**Comment by nikirova** [comment] 2017-05-24 06:50
Sorry, but I cannot see in your message what capabilities you are using!

**Comment by BlueBasher** [comment] 2017-05-24 08:40
My bad, the 3 capabilities that I enabled are: internetClient, internetClientServer, privateNetworkClientServer
Not sure if all of them are required though, perhaps internetClientServer is not necessary.

**Comment by DennisSc** [comment] 2017-06-09 17:41
HEy guys,

recently had the same problem. I think that it is by design - universal apps cannot communicate with each other due to app container isolation... with loopbackexemption you can connect to other (non-UAP) applications, but not to other UAP apps on the same host.

To solve this, you can either
-proxy the connection via a second machine (works)
-implement broker and client in same UAP app (works too - AFAIK this is the only possibility for UAP to connect to "localhost")

regards

**Comment by VladimirAkopyan** [comment] 2017-09-27 15:19
Universal apps cannot communicate with each other - we need to provide a properAPI for your usecase, #47 
Otherwise I am closing this issue.

**Closed by VladimirAkopyan** 2017-09-27 15:19 UTC
