### ISSUE TITLE
Broker and Client on same device not connecting

### ISSUE THREAD

**Issue by Schwimo** [gnatmq/gnatmq#33] opened 2017-01-24 07:48 UTC
When I start an Broker (BackgroundApplication Windows 10 IoT) and want to connect to it with localhost from an UWP app, there occurs an timeout.

I have an Pi3 with the latest Windows 10 IoT installed.

**Comment by fastlink30** [comment] 2017-01-24 08:02
did you try to substitute 'localhost' with the ip of the machine? i have the same problem, solved give the ip of broker machine

**Comment by Schwimo** [comment] 2017-01-24 08:04
Yes i tried that as well. Do you use an UWP or BackgroundApplication? Because with a normal Console Application it works well.

I also have set the permissions. If your solution works, can you upload it somehow? @fastlink30

**Comment by fastlink30** [comment] 2017-01-24 08:11
is a winform application with embedded qnatmq, not working on background, so quite different from w10 iot, sorry, never tried with w10 iot

**Comment by toran73** [comment] 2017-01-24 09:21
Okej, I have similar but different problem and it has to do with the "loopback exempt" and running the application using remote debugger.. I can get it to work if i'm not running the application through remotedebugger.. is it the same scenario for you?

**Comment by Schwimo** [comment] 2017-01-28 10:56
No, I can't get it to work but I think the problem is described in the following post: http://stackoverflow.com/questions/32665847/cannot-connect-to-streamsocketlistener

**Comment by chkr1011** [comment] 2017-03-03 23:46
Hi, 
please look at my issue [38](https://github.com/ppatierno/gnatmq/issues/38). There I described how to use the Broker and Client on the same Windows 10 IoT Core device. 

Best regards,
Christian

**Comment by VladimirAkopyan** [comment] 2017-09-27 15:35
Basically duplicate of the same problem. Closing it.

**Closed by VladimirAkopyan** 2017-09-27 15:35 UTC
Labels: Documentation, duplicate
